---
debug: true
fallball_service_url: http://romanovskyj.ru:8002/v1/ 
fallball_service_authorization_token: 0d44e92a438a9247209447f2b298a10885e8c1a0
oauth_key: eromanovskyj-test-activation-v1- 
oauth_secret: d69a543b738b4a03be6d0c4c3feae3f3
diskspace_resource: DISKSPACE
users_resource: USERS
gold_users_resource: GOLD_USERS
devices_resource: DEVICES
default_user_limit: 10
gold_user_limit: 15
